<?php

namespace Znieh\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendsLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsLinkRepository extends EntityRepository
{
}
