<?php

namespace Znieh\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendsLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsLinkRepository extends EntityRepository
{
	public function findDouble($slug, $user)
  	{
		  $qb = $this->_em->createQueryBuilder();

		  $qb->select('a')
		     ->from('ZniehUserBundle:FriendsLink', 'a')
		    ->where($qb->expr()->andX(
		    							$qb->expr()->eq('a.user1', '?1'),
		    							$qb->expr()->eq('a.user2', '?2')
		    							))
			->orWhere($qb->expr()->andX(
										$qb->expr()->eq('a.user1', '?3'),
										$qb->expr()->eq('a.user2', '?4')
										))
			->setParameter(1, $user)
			->setParameter(2, $slug)
			->setParameter(3, $slug)
			->setParameter(4, $user);		

			return $qb->getQuery()
		              ->getOneOrNullResult();
  	}

  	public function findFriends($slug)
  	{
		  $qb = $this->_em->createQueryBuilder();

		  $qb->select('a')
		     ->from('ZniehUserBundle:FriendsLink', 'a')
		    ->where($qb->expr()->orX(
		    							$qb->expr()->eq('a.user1', '?1'),
		    							$qb->expr()->eq('a.user2', '?2')
		    						))
			->setParameter(1, $slug)
			->setParameter(2, $slug);		

			return $qb->getQuery()
		              ->getResult();
  	}
}
