<?php

namespace Znieh\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findUserWithRessources($slug)
	{

	    $query = $this->createQueryBuilder('u')
	                  ->leftJoin('u.ressource', 'r')
	                   ->addSelect('r')
                   	   ->where('u.usernameCanonical = '.$slug)
	                  ->getQuery();

	    return $query->getResult();
	}
}
