<?php

namespace Znieh\VillageGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArmorPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmorPartRepository extends EntityRepository
{
	public function findUnlockedsByUserAndType($userId, $typeId)
	{
	    $qb = $this->createQueryBuilder('a');
	    $query =  $qb->leftJoin('a.type', 't')
	    			 ->addSelect('t')
	    			 ->leftJoin('a.unlockeds', 'u')
	    			 ->addSelect('u')
	    			 ->leftJoin('u.user', 'us')
	    			 ->addSelect('us')
	                 ->where($qb->expr()->eq('t.id', $typeId))
	                 ->andWhere($qb->expr()->eq('us.id', $userId))
	                 ;
	    return $query;
	}
}
