<?php

namespace Znieh\VillageGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameObjectRepository extends EntityRepository
{
    public function findObjectsByBuilding($building)
    {
      $qb = $this->createQueryBuilder('g');
      $query =  $qb->leftJoin('g.step', 's')
                   ->where($qb->expr()->eq('s.building', $building))
                   ->getQuery();
      return $query->getResult();
    }
}
