<?php

namespace Znieh\VillageGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InsignaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsignaRepository extends EntityRepository
{
    public function findUnlockedsByUser($userId)
    {
      $qb = $this->createQueryBuilder('r');
      $query =  $qb->leftJoin('r.unlockeds', 'u')
	    			 ->addSelect('u')
	    			 ->leftJoin('u.user', 'us')
	    			 ->addSelect('us')
                   ->where($qb->expr()->eq('us.id', $userId))
                   ;
      return $query;
    }
}
