<?php

namespace Znieh\VillageGameBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends NestedTreeRepository
{
  public function findAllByBuilding($building)
  {
    $qb = $this->createQueryBuilder('s');
    $query =  $qb->where($qb->expr()->eq('s.building', $building))
                 ->getQuery();
    return $query->getResult();
  }
}
