<?php

namespace Znieh\VillageGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnlockedGameObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnlockedGameObjectRepository extends EntityRepository
{
}
