<?php

namespace Znieh\UnitGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SavedTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavedTeamRepository extends EntityRepository
{
}
