<?php

namespace Znieh\UnitGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
  public function findOneByUserSelected($user)
   {
     $qb = $this->createQueryBuilder('t');
     $query = $qb
                 ->leftJoin('t.user', 'u')
                  ->addSelect('u')
                 ->leftJoin('t.units', 'un')
                  ->addSelect('un')
                 ->where($qb->expr()->eq('u.id', $user))
                 ->andWhere($qb->expr()->eq('t.selected', 1))
                 ->getQuery();
     return $query->setMaxResults(1)->getResult();
   }
}
