<?php

namespace Znieh\UnitGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends EntityRepository
{

	public function findAllByUser($userId)
	 {
	   $qb = $this->createQueryBuilder('t');
	   $query = $qb->leftJoin('t.user', 'u')
	               ->addSelect('u')
	               ->where($qb->expr()->eq('u.id', $userId))
					;
	   return $query;
	 }
}
