<?php

namespace Znieh\UnitGameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends EntityRepository
{
  public function findByUserByBuilding($user, $building)
   {
     $qb = $this->createQueryBuilder('w');
     $query = $qb
                 ->leftJoin('w.user', 'u')
                  ->addSelect('u')
                 ->leftJoin('w.parts', 'p')
                  ->addSelect('p')
                 ->leftJoin('p.type', 't')
                  ->addSelect('t')
                 ->leftJoin('t.types', 'tt')
                  ->addSelect('tt')
                 ->leftJoin('tt.building', 'b')
                  ->addSelect('b')
                 ->where($qb->expr()->eq('u.id', $user))
                 ->andWhere($qb->expr()->eq('b.id', $building))
                 ->getQuery();
     return $query->getResult();
   }

   public function findAllByUser($user)
    {
      $qb = $this->createQueryBuilder('w');
      $query = $qb
                  ->leftJoin('w.user', 'u')
                   ->addSelect('u')
                  ->where($qb->expr()->eq('u.id', $user))
                  ;
      return $query;
    }
}
